spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        default_batch_fetch_size: 100 # Fetch Join
        format_sql: 'true'
        use_sql_comments: 'true'
    show-sql: 'true'
    open-in-view: 'false'

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: '1234'
    username: poly
    jdbc-url: jdbc:mariadb://192.168.152.128:3306/communityDB

  second-datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: '1234'
    username: poly
    jdbc-url: jdbc:mariadb://192.168.152.129:3306/userDB

  # Server Name
  application:
    name: COMMUNITY-SERVICE


api:
  gateway: localhost:11000