spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100 # Fetch Join
        format_sql: 'true'
        use_sql_comments: 'true'
    show-sql: 'true'
    open-in-view: 'false'

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: '22c1f8afca7a2736e6d368264a2ce210fe65c8f8'
    username: bonobonoCommunity_lovelyany
    url: jdbc:mariadb://zoj.h.filess.io:3305/bonobonoCommunity_lovelyany

  # Server Name
  application:
    name: COMMUNITY-CQRS-SERVICE


api:
  gateway: localhost:11000