spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100 # Fetch Join
        format_sql: 'true'
        use_sql_comments: 'true'
    show-sql: 'true'
    open-in-view: 'false'

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: '1234'
    username: poly
    url: jdbc:mariadb://localhost:3306/myDB

  # Server Name
  application:
    name: USER-SERVICE
